development:
  adapter: postgresql
  database: omniauthsample_dev
  host: localhost
  user: igarashi
  password:
  encoding: utf8
  
test:
  adapter: postgresql
  database: omniauthsample_test
  host: localhost
  user: igarashi
  password:
  encoding: utf8
  
production:
  adapter: postgresql
  database: omniauthsample_dev
  host: localhost
  user: igarashi
  password:
  encoding: utf8
  